/* eslint-disable @next/next/no-html-link-for-pages, @next/next/no-img-element */
import type { Metadata } from 'next';
import { notFound } from 'next/navigation';
import { Header, Footer, FlowRail, WorkflowForm, FAQ, WorkflowEvidence } from '../components';

type PageData={eyebrow:string;title:string;intro:string;kind?:string;bullets?:string[];flow?:string[];project?:string;image?:string;alt?:string};

const projects:Record<string,PageData>={
  'customer-inquiry-orchestration':{eyebrow:'CUSTOMER OPERATIONS',title:'Customer Inquiry Orchestration',intro:'An AI receptionist receives incoming chat messages and an intent router directs each enquiry to the appropriate lead qualification, support, meeting, or general-inquiry workflow.',flow:['Chat received','Receptionist agent','Intent router','Specialist workflow'],bullets:['Reduce manual chat sorting','Direct requests to the correct process','Maintain context through model and memory','Separate sales, support, meeting, and general intent'],image:'/assets/customer-inquiry-orchestration.png',alt:'Customer inquiry workflow connecting an incoming chat, AI receptionist, memory, intent routing, and lead, support, meeting, or general enquiry workflows.'},
  'ai-lead-qualification-crm-automation':{eyebrow:'REVENUE OPERATIONS',title:'AI Lead Qualification & CRM Automation',intro:'A connected revenue workflow that analyses form submissions, structures lead data, checks Pipedrive records, creates or updates deals, routes leads, sends Slack and Gmail notifications, and records outcomes in Google Sheets.',flow:['Form submission','Lead analysis','CRM check','Conditional route','Team notification','Record outcome'],bullets:['Consistent qualification','Clearer routing','Cleaner CRM movement','Relevant team notifications','Clear lead records'],image:'/assets/ai-lead-qualification-crm.png',alt:'AI lead qualification workflow connecting form submission, LLM analysis, Pipedrive records, Slack alerts, Gmail notifications, and Google Sheets logging.'},
  'finance-email-processing':{eyebrow:'INTERNAL OPERATIONS',title:'Finance Email Processing Automation',intro:'A document-processing workflow retrieves finance emails and attached PDFs, transforms and interprets the content, validates the result, records it, and sends an alert.',flow:['Gmail trigger','Conditional check','Extract PDF','HTTP / OCR','Transform','Interpret','Validate','Record & alert'],bullets:['Reduce repetitive attachment handling','Convert unstructured documents into structured data','Validate results','Create finance records','Notify the appropriate team'],image:'/assets/finance-email-processing.png',alt:'Finance email workflow connecting Gmail, PDF extraction, HTTP processing, JavaScript transformation, LLM interpretation, validation, Google Sheets, and finance alerts.'},
  'document-ingestion-processing':{eyebrow:'CUSTOM AI SYSTEMS',title:'Document Ingestion & Processing',intro:'A controlled pipeline prepares documents for knowledge retrieval by extracting and cleaning content, adding metadata, processing it through HTTP, and sending it to a target knowledge or vector system.',flow:['Manual trigger','Read files','Extract PDF text','Clean & chunk','Add metadata','HTTP processing','JavaScript transform','Target knowledge system'],bullets:['Prepare documents for knowledge retrieval','Standardize content','Create usable chunks','Attach relevant metadata','Move processed content to target storage'],image:'/assets/document-ingestion-processing.png',alt:'Document ingestion pipeline from manual trigger and local files through PDF extraction, chunking, metadata, HTTP processing, JavaScript transformation, and target knowledge storage.'}
};

const pages:Record<string,PageData>={
  'solutions':{eyebrow:'SOLUTIONS',title:'Connected systems for the work your business repeats.',intro:'BuildFlow engineers complete handoffs across revenue, client, internal, and knowledge operations.',kind:'solutions'},
  'solutions/revenue-operations':{eyebrow:'REVENUE OPERATIONS',title:'Move every qualified opportunity to the right next step.',intro:'Connect lead capture, enrichment, qualification, routing, CRM synchronization, follow-up, appointments, and sales visibility.',flow:['Enquiry','Qualify','Route','CRM','Follow-up'],bullets:['Leads wait for assignment','CRM records are incomplete','Follow-ups depend on memory','Teams lack a clear next owner'],project:'ai-lead-qualification-crm-automation'},
  'solutions/client-operations':{eyebrow:'CLIENT OPERATIONS',title:'Make every new client feel expected.',intro:'Create a coordinated journey from proposal and agreement through payment, intake, documents, project creation, welcome communication, approvals, and status updates.',flow:['Agreement','Intake','Onboard','Coordinate','Deliver'],bullets:['Intake arrives in different places','Approvals need chasing','Project setup is repeated manually','Clients lack timely status'],project:'customer-inquiry-orchestration'},
  'solutions/internal-operations':{eyebrow:'INTERNAL OPERATIONS',title:'Remove the coordination surrounding the real work.',intro:'Connect requests, approvals, reporting, data synchronization, task routing, notifications, recurring administration, and management visibility.',flow:['Request','Verify','Approve','Assign','Complete'],bullets:['Requests have no owner','Reports require copying','Systems drift out of sync','Exceptions become visible too late'],project:'finance-email-processing'},
  'solutions/custom-ai-systems':{eyebrow:'CUSTOM AI SYSTEMS',title:'Use AI where normal automation reaches its limit.',intro:'Build focused systems for document extraction, classification, knowledge retrieval, structured summarization, internal assistance, and controlled agent workflows.',flow:['Context','Retrieve','Interpret','Review','Assist'],bullets:['Unstructured content blocks rules','Knowledge is difficult to retrieve','Outputs need controlled formats','Important decisions need review'],project:'document-ingestion-processing'},
  'who-we-help':{eyebrow:'WHO WE HELP',title:'For service businesses growing beyond manual coordination.',intro:'BuildFlow is most useful when a process is stable enough to understand, frequent enough to matter, and valuable enough to engineer properly.',kind:'audiences'},
  'who-we-help/marketing-agencies':{eyebrow:'MARKETING AGENCIES',title:'Let your team deliver the work—not spend the day moving it.',intro:'Connect lead intake, qualification, CRM movement, sales handoffs, onboarding, approvals, reporting, and recurring communication.',flow:['Lead','Qualify','Sell','Onboard','Deliver'],bullets:['Multiple lead sources','Sales-to-delivery gaps','Approvals delay campaigns','Reporting is assembled manually'],project:'ai-lead-qualification-crm-automation'},
  'who-we-help/professional-services':{eyebrow:'PROFESSIONAL SERVICES',title:'Create a smoother operation around expert work.',intro:'Coordinate enquiries, proposals, intake, documents, approvals, delivery, and client communication without turning experts into process managers.',flow:['Enquiry','Scope','Engage','Deliver','Update'],bullets:['Experts chase information','Client intake varies','Documents arrive unstructured','Status communication is manual'],project:'document-ingestion-processing'},
  'who-we-help/recruitment':{eyebrow:'RECRUITMENT & STAFFING',title:'Keep candidates, clients, and internal teams moving together.',intro:'Create clearer routes across requests, candidate information, review, communication, scheduling, and ownership.',flow:['Request','Match','Review','Coordinate','Progress'],bullets:['Information is re-entered','Ownership changes silently','Scheduling creates delay','Updates depend on memory'],project:'customer-inquiry-orchestration'},
  'who-we-help/real-estate':{eyebrow:'PROPERTY TEAMS',title:'Make every enquiry reach the right next action.',intro:'Route buyer, seller, tenant, and general enquiries according to intent while preserving context and clear ownership.',flow:['Enquiry','Identify intent','Route','Assign','Follow up'],bullets:['Enquiries arrive across channels','Intent is sorted manually','Ownership is unclear','Follow-up timing varies'],project:'customer-inquiry-orchestration'},
  'approach':{eyebrow:'PROCESS BEFORE TECHNOLOGY',title:'Build the right system—not the fastest automation.',intro:'A broken process does not improve merely because it runs automatically.',kind:'approach'},
  'about':{eyebrow:'ABOUT BUILDFLOW AI',title:'Good automation begins with understanding the work.',intro:'BuildFlow AI is founded by Hanan Naseer, an AI automation specialist focused on connected operational systems for growing businesses.',kind:'about'},
  'workflow-review':{eyebrow:'WORKFLOW REVIEW',title:'Show us where work gets stuck.',intro:'Briefly describe the process, tools, and handoffs involved. We will assess whether automation, AI, process redesign—or a simpler solution—is the appropriate next step.',kind:'form'},
  'thank-you':{eyebrow:'WORKFLOW REVIEW',title:'Your workflow is ready for the next conversation.',intro:'Based on the information provided, the process appears suitable for a Workflow Mapping Call. Calendar scheduling will appear here once a real calendar integration is configured.',kind:'thanks'},
  'thank-you/manual-review':{eyebrow:'WORKFLOW REVIEW',title:'We have received the process details.',intro:'The workflow will be reviewed to determine whether custom automation, AI, process redesign, or another approach is the best fit.',kind:'thanks'},
  'privacy':{eyebrow:'LEGAL DRAFT',title:'Privacy Policy',intro:'How BuildFlow AI collects, uses, stores, and protects workflow-review enquiry information.',kind:'privacy'},
  'terms':{eyebrow:'LEGAL DRAFT',title:'Terms',intro:'Launch terms for using the BuildFlow AI website and reviewing its engineering portfolio.',kind:'terms'}
};

const solutionLinks=[['Revenue Operations','/solutions/revenue-operations'],['Client Operations','/solutions/client-operations'],['Internal Operations','/solutions/internal-operations'],['Custom AI Systems','/solutions/custom-ai-systems']];
const audienceLinks=[['Marketing Agencies','/who-we-help/marketing-agencies'],['Professional Services','/who-we-help/professional-services'],['Recruitment & Staffing','/who-we-help/recruitment'],['Property Teams','/who-we-help/real-estate']];

export async function generateMetadata({params}:{params:Promise<{slug?:string[]}>}):Promise<Metadata>{const {slug=[]}=await params;const path=slug.join('/');const d=path===''?{title:'BuildFlow AI',intro:'AI Operations Engineering for growing service businesses.'}:path==='work'?{title:'Automation Systems and Case Studies',intro:'Real connected workflow systems from BuildFlow AI.'}:path.startsWith('work/')?projects[path.slice(5)]:pages[path];if(!d)return{title:'Page not found',robots:{index:false,follow:false}};const title=path===''?'BuildFlow AI | AI Operations Engineering':path==='about'?'About BuildFlow AI and Hanan Naseer':path==='workflow-review'?'Map Your Workflow':d.title;const canonical=`/${path}`;return{title,description:d.intro,alternates:{canonical},openGraph:{title,description:d.intro,type:'website',url:canonical},twitter:{card:'summary_large_image',title,description:d.intro}}}

export default async function CatchAll({params}:{params:Promise<{slug?:string[]}>}){const {slug=[]}=await params; const path=slug.join('/'); if(path==='')return <Home/>; if(path==='work')return <Work/>; if(path.startsWith('work/')){const p=projects[path.slice(5)];if(!p)notFound();return <Project data={p}/>};const p=pages[path];if(!p)notFound();return <Standard data={p}/>}

function Shell({children}:{children:React.ReactNode}){return <><Header/><main id="main">{children}</main><Footer/></>}
const CTA=()=> <section className="final-cta dark"><div className="wrap narrow"><p className="eyebrow">START WITH THE PROCESS</p><h2>Show us where work gets stuck.</h2><p>Tell us what begins the process, where the handoffs slow down, and what should happen next.</p><div className="actions"><a className="button" href="/workflow-review">Map Your Workflow <span>→</span></a><a className="text-link" href="/work">See Our Work →</a></div><small>No passwords, API keys, or confidential customer records are required.</small></div></section>;

function Home(){return <Shell><section className="hero dark"><div className="wrap hero-grid"><div><p className="eyebrow">AI OPERATIONS ENGINEERING FOR GROWING SERVICE BUSINESSES</p><h1>Work should flow.<span>Not be chased.</span></h1><p className="lead desktop-copy">BuildFlow AI engineers the handoffs between your tools, teams, and customers—turning manual coordination into connected systems that keep work moving.</p><p className="lead mobile-copy">We connect the handoffs between your tools, teams, and customers—so work keeps moving. Rules handle consistency. AI handles interpretation. Your team keeps control.</p><div className="actions"><a className="button" href="/workflow-review">Map Your Workflow <span>→</span></a><a className="text-link" href="/work">See Our Work →</a></div><p className="trust">Built around your existing tools. Designed for human control. Engineered for reliable operation.</p></div><FlowRail hero/></div></section>
<section className="light"><div className="wrap"><p className="eyebrow">WHERE WORK BREAKS</p><h2>Work stops at the handoff.</h2><p className="section-intro">Most delays begin in the space between tasks—when information must be copied, someone needs reminding, an approval is waiting, or the next person does not know it is their turn.</p><div className="break-grid">{['Information lives in separate tools.','The next action depends on memory.','Routine decisions create unnecessary waiting.','Managers see the delay after it becomes a problem.'].map((x,i)=><article key={x}><span>0{i+1}</span><div className="mini-route"><i>Input</i><b>{i===2?'Approval':i===3?'Escalation':'Waiting'}</b></div><h3>{x}</h3></article>)}</div><p className="closing">Your team should run the operation—not spend the day holding it together.</p></div></section>
<section className="paper"><div className="wrap split"><div><p className="eyebrow">FROM TRIGGER TO OUTCOME</p><h2>Engineer what happens next.</h2><p>A single automated task is not an operational system. The value comes from connecting the full journey—including decisions, tools, people, and failure paths.</p></div><FlowRail labels={['Capture','Verify','Decide','Route','Act','Confirm']}/></div></section>
<section className="light"><div className="wrap"><p className="eyebrow">WHAT WE BUILD</p><h2>Connected systems for the work your business repeats.</h2><div className="chapters">{solutionLinks.map(([n,h],i)=><a href={h} key={n}><span>0{i+1}</span><h3>{n}</h3><FlowRail labels={i===0?['Enquiry','Qualify','Route','CRM','Follow-up']:i===1?['Agreement','Intake','Onboard','Coordinate','Deliver']:i===2?['Request','Verify','Approve','Assign','Complete']:['Context','Retrieve','Interpret','Review','Assist']}/><b>Explore {n} →</b></a>)}</div></div></section>
<section className="dark logic"><div className="wrap"><p className="eyebrow">THE RIGHT LOGIC FOR EVERY STEP</p><h2>Not every step needs AI.</h2><div className="logic-grid"><article><i className="cobalt">RULES</i><h3>Predictable execution</h3><p>Validation · Synchronization · Routing · Task creation · Status updates</p></article><article><i className="cobalt">AI</i><h3>Useful interpretation</h3><p>Extract · Categorize · Understand · Summarize · Retrieve knowledge</p></article><article><i className="amber">PEOPLE</i><h3>Judgment and accountability</h3><p>Approve · Review uncertainty · Handle exceptions · Override · Decide</p></article></div><p className="closing">Your team makes the decisions. <span>The system moves the work.</span></p></div></section>
<section className="paper"><div className="wrap"><p className="eyebrow">FEATURED SYSTEM</p><h2>A lead should not wait for the next manual step.</h2><WorkflowEvidence src="/assets/ai-lead-qualification-crm.png" alt={projects['ai-lead-qualification-crm-automation'].alt!} loading="eager"/><h3>AI Lead Qualification & CRM Automation</h3><p className="section-intro">Form submission → LLM-assisted analysis → structured response → Pipedrive check → create or update records → conditional routing → Slack and Gmail notifications → Google Sheets record.</p><a className="text-link ink" href="/work/ai-lead-qualification-crm-automation">View the System →</a></div></section>
<Method/><Work condensed/><Founder/><FAQ/><CTA/></Shell>}

function Method(){return <section className="light"><div className="wrap"><p className="eyebrow">HOW WE WORK</p><h2>From scattered process to working system.</h2><div className="steps">{[['01','Map'],['02','Redesign'],['03','Engineer'],['04','Validate'],['05','Operate']].map(([n,x])=><article key={n}><span>{n}</span><h3>{x}</h3><p>{x==='Map'?'Understand the process, people, tools, and friction.':x==='Redesign'?'Remove unnecessary movement and define a clearer future state.':x==='Engineer'?'Connect tools, rules, AI, custom logic, and people.':x==='Validate'?'Test normal paths, missing data, failures, uncertainty, and approvals.':'Launch with visibility, documentation, ownership, and a path to improve.'}</p></article>)}</div></div></section>}
function Founder(){return <section className="light founder"><div className="wrap split"><div className="portrait"><img src="/assets/hanan-naseer-founder.png" alt="Hanan Naseer, founder and AI Operations Engineer at BuildFlow AI"/></div><div><p className="eyebrow">FOUNDER-LED</p><h2>Direct thinking. Direct accountability.</h2><p>BuildFlow AI is founded by Hanan Naseer, an AI automation specialist focused on building connected operational systems for growing businesses.</p><p>Every engagement begins with the process—not a pre-built package or a preferred tool.</p><ul>{['Process before technology','Selective AI instead of AI everywhere','Human control for important decisions','Honest evidence instead of inflated claims'].map(x=><li key={x}>{x}</li>)}</ul><a className="text-link ink" href="/about">About BuildFlow AI →</a></div></div></section>}

function Work({condensed=false}:{condensed?:boolean}){return <Shellless shell={!condensed}><section className="paper work"><div className="wrap"><p className="eyebrow">SYSTEMS IN PRACTICE</p><h2>Real workflows. Clearly explained.</h2><div className="project-list">{Object.entries(projects).map(([slug,p],i)=><article key={slug}><div><span className="index">0{i+1}</span><p className="eyebrow">{p.eyebrow}</p><h3>{p.title}</h3><p>{p.intro}</p><a className="text-link ink" href={`/work/${slug}`}>View Project →</a></div><WorkflowEvidence src={p.image!} alt={p.alt!}/></article>)}</div></div></section>{!condensed&&<CTA/>}</Shellless>}
function Shellless({shell,children}:{shell:boolean;children:React.ReactNode}){return shell?<Shell>{children}</Shell>:<>{children}</>}

function Project({data}:{data:PageData}){return <Shell><section className="page-hero dark"><div className="wrap narrow"><p className="eyebrow">{data.eyebrow} · PORTFOLIO SYSTEM</p><h1>{data.title}</h1><p className="lead">{data.intro}</p></div></section><section className="paper"><div className="wrap"><WorkflowEvidence src={data.image!} alt={data.alt!} large loading="eager"/><FlowRail labels={data.flow}/></div></section><section className="light"><div className="wrap two-col"><article><p className="eyebrow">WHERE WORK GETS STUCK</p><h2>Before the connected system</h2><p>Information, decisions, ownership, and next actions can become separated across tools. The workflow creates a visible route from trigger to outcome.</p></article><article><p className="eyebrow">SYSTEM OUTCOME</p><h2>A clearer operational route</h2><ul>{data.bullets?.map(x=><li key={x}>{x}</li>)}</ul></article></div></section><section className="dark"><div className="wrap"><p className="eyebrow">CONTROL MODEL</p><h2>Rules, AI, and people have distinct roles.</h2><div className="logic-grid"><article><i className="cobalt">RULES</i><p>Move structured data and apply known conditions.</p></article><article><i className="cobalt">AI</i><p>Interpret unstructured context only where shown in the workflow.</p></article><article><i className="amber">PEOPLE</i><p>Own judgment, exceptions, sensitive actions, and final accountability.</p></article></div><p className="note">Technology shown is limited to the applications and processing steps visible in the project evidence.</p></div></section><CTA/></Shell>}

function Standard({data}:{data:PageData}){if(data.kind==='form')return <Shell><section className="form-hero light"><div className="wrap narrow"><p className="eyebrow">{data.eyebrow}</p><h1>{data.title}</h1><p className="lead">{data.intro}</p><WorkflowForm/></div></section></Shell>;const legal=data.kind==='privacy'||data.kind==='terms';return <Shell><section className="page-hero dark"><div className="wrap narrow"><p className="eyebrow">{data.eyebrow}</p><h1>{data.title}</h1><p className="lead">{data.intro}</p>{!legal&&data.kind!=='thanks'&&<div className="actions"><a className="button" href="/workflow-review">Map Your Workflow →</a></div>}</div></section>{data.kind==='solutions'?<Directory items={solutionLinks}/>:data.kind==='audiences'?<Directory items={audienceLinks}/>:data.kind==='approach'?<Method/>:data.kind==='about'?<About/>:legal?<Legal type={data.kind as 'privacy'|'terms'}/>:data.kind==='thanks'?<Thanks/>:<Detail data={data}/>} {!legal&&data.kind!=='thanks'&&<CTA/>}</Shell>}
function Directory({items}:{items:string[][]}){return <section className="light"><div className="wrap"><div className="directory">{items.map(([n,h],i)=><a key={n} href={h}><span>0{i+1}</span><h2>{n}</h2><p>See the operational friction, system map, control model, relevant evidence, and fit criteria.</p><b>Explore →</b></a>)}</div></div></section>}
function Detail({data}:{data:PageData}){const pr=data.project?projects[data.project]:null;return <><section className="paper"><div className="wrap split"><div><p className="eyebrow">TYPICAL PROCESS MAP</p><h2>From trigger to controlled outcome.</h2><FlowRail labels={data.flow}/></div><div><p className="eyebrow">SIGNS THE PROCESS IS BREAKING</p><ul>{data.bullets?.map(x=><li key={x}>{x}</li>)}</ul></div></div></section><section className="light"><div className="wrap"><p className="eyebrow">RESPONSIBILITIES</p><h2>The right mechanism for each step.</h2><div className="logic-grid"><article><i className="cobalt">RULES</i><p>Validation, routing, synchronization, records, and approved communication.</p></article><article><i className="cobalt">AI</i><p>Interpretation, extraction, classification, and useful context.</p></article><article><i className="amber">PEOPLE</i><p>High-value judgment, uncertainty, exceptions, and sensitive actions.</p></article></div></div></section>{pr&&<section className="paper"><div className="wrap"><p className="eyebrow">RELEVANT SYSTEM</p><h2>{pr.title}</h2><div className="evidence"><img src={pr.image} alt={pr.alt}/></div><a className="text-link ink" href={`/work/${data.project}`}>View Project →</a></div></section>}<Method/></>}
function About(){return <><Founder/><section className="paper"><div className="wrap two-col"><article><p className="eyebrow">WHY BUILDFLOW EXISTS</p><h2>Operational clarity before technical complexity.</h2><p>BuildFlow AI helps growing service businesses replace fragile manual coordination with connected systems that keep important decisions visible.</p><p>Based in Pakistan and working remotely with businesses internationally.</p></article><article><p className="eyebrow">WHAT WE WILL NOT BUILD</p><ul>{['Deceptive automation or impersonation','Spam systems','Systems designed to exploit users','Sensitive autonomous decisions without safeguards','Needlessly complex AI where a rule works better'].map(x=><li key={x}>{x}</li>)}</ul></article></div></section></>}
function Legal({type}:{type:'privacy'|'terms'}){return <section className="light legal-copy"><div className="wrap narrow"><div className="legal-note"><strong>Launch draft — professional legal review required.</strong><p>Effective date: to be confirmed following legal review.</p></div>{type==='privacy'?<><h2>How this website handles information</h2><p>The workflow review collects process details and business contact information so BuildFlow AI can assess and respond to an enquiry. Please do not submit passwords, customer records, or confidential documents.</p><p>Submissions are stored in Cloudflare D1. Cloudflare Turnstile may process technical anti-abuse signals. BuildFlow AI does not sell personal information and does not add submitters to a marketing subscription by default.</p><p>A final retention period is still to be decided during legal review. To request access, correction, or deletion, email <a href="mailto:hanannaseer778@gmail.com">hanannaseer778@gmail.com</a>.</p></>:<><h2>Website use and portfolio terms</h2><p>This website provides general information about BuildFlow AI services and illustrative engineering portfolio examples. It does not guarantee a business, financial, operational, or technical outcome.</p><p>BuildFlow AI names, copy, and original materials are protected by applicable intellectual-property rights. Do not misuse the website, attempt unauthorized access, disrupt its operation, or submit unlawful material. External links are provided for convenience and remain under their owners’ control.</p><p>Any limitation-of-liability language and governing terms require professional legal review before final adoption. Questions can be sent to <a href="mailto:hanannaseer778@gmail.com">hanannaseer778@gmail.com</a>.</p></>}</div></section>}
function Thanks(){return <section className="light"><div className="wrap narrow"><div className="success-note"><strong>Workflow details received.</strong><p>Your submission reference is shown in the page address. BuildFlow AI will review the process and respond using the contact details you supplied. No calendar booking or email delivery is implied.</p><p>For direct contact, email <a href="mailto:hanannaseer778@gmail.com">hanannaseer778@gmail.com</a>.</p></div></div></section>}
