import assert from "node:assert/strict";
import { existsSync, readFileSync } from "node:fs";
import test from "node:test";
const page=readFileSync(new URL("../app/[[...slug]]/page.tsx",import.meta.url),"utf8");
const components=readFileSync(new URL("../app/components.tsx",import.meta.url),"utf8");
const required=["solutions","solutions/revenue-operations","solutions/client-operations","solutions/internal-operations","solutions/custom-ai-systems","who-we-help","who-we-help/marketing-agencies","who-we-help/professional-services","who-we-help/recruitment","who-we-help/real-estate","customer-inquiry-orchestration","ai-lead-qualification-crm-automation","finance-email-processing","document-ingestion-processing","approach","about","workflow-review","thank-you","thank-you/manual-review","privacy","terms"];
test("all required routes have page-specific data",()=>{for(const route of required)assert.ok(page.includes(`'${route}'`)||page.includes(`'${route.replace('work/','')}'`),route)});
test("production form and accessible evidence are wired",()=>{assert.match(components,/fetch\('\/api\/workflow-review'/);assert.match(components,/showModal\(\)/);assert.match(components,/TURNSTILE_SITE_KEY/);assert.doesNotMatch(page+components,/preview cannot send|backend is not connected/i)});
test("verified assets and contacts",()=>{for(const asset of ["hanan-naseer-founder.png","customer-inquiry-orchestration.png","ai-lead-qualification-crm.png","finance-email-processing.png","document-ingestion-processing.png"])assert.ok(existsSync(new URL(`../public/assets/${asset}`,import.meta.url)));assert.match(page+components,/hanannaseer778@gmail\.com/);assert.match(page+components,/linkedin\.com\/in\/hnautomation/);assert.doesNotMatch(page+components,/whatsapp|wa\.me/i);assert.match(page,/document-ingestion-processing\.png/)});
